const {Schema} = require("mongoose");
const {MessageEntity} = require("./MessageEntity");
const {LabeledPrice} = require("./LabeledPrice");
module.exports = {
  InputMessageContent: new Schema({
    message_text: {type: String},
    parse_mode: {type: String},
    entities: {type: [MessageEntity]},
    disable_web_page_preview: {type: Boolean},
    latitude: {type: Number},
    longitude: {type: Number},
    horizontal_accuracy: {type: Number},
    live_period: {type: Number},
    heading: {type: Number},
    proximity_alert_radius: {type: Number},
    title: {type: String},
    address: {type: String},
    foursquare_id: {type: String},
    foursquare_type: {type: String},
    google_place_id: {type: String},
    google_place_type: {type: String},
    phone_number: {type: String},
    first_name: {type: String},
    last_name: {type: String},
    vcard: {type: String},
    description: {type: String},
    payload: {type: String},
    provider_token: {type: String},
    currency: {type: String},
    prices: {type: [this.LabeledPrice]},
    max_tip_amount: {type: Number},
    suggested_tip_amounts: {type: Number},
    provider_data: {type: String},
    photo_url: {type: String},
    photo_size: {type: Number},
    photo_width: {type: Number},
    photo_height: {type: Number},
    need_name: {type: Boolean},
    need_phone_number: {type: Boolean},
    need_email: {type: Boolean},
    need_shipping_address: {type: Boolean},
    send_phone_number_to_provider: {type: Boolean},
    send_email_to_provider: {type: Boolean},
    is_flexible: {type: Boolean}
  }),
  InputTextMessageContent: new Schema({
    message_text: {type: String},
    parse_mode: {type: String},
    entities: {type: [MessageEntity]},
    disable_web_page_preview: {type: Boolean}
  }),
  InputLocationMessageContent: new Schema({
    latitude: {type: Number},
    longitude: {type: Number},
    horizontal_accuracy: {type: Number},
    live_period: {type: Number},
    heading: {type: Number},
    proximity_alert_radius: {type: Number}
  }),
  InputVenueMessageContent: new Schema({
    latitude: {type: Number},
    longitude: {type: Number},
    title: {type: String},
    address: {type: String},
    foursquare_id: {type: String},
    foursquare_type: {type: String},
    google_place_id: {type: String},
    google_place_type: {type: String}
  }),
  InputContactMessageContent: new Schema({
    phone_number: {type: String},
    first_name: {type: String},
    last_name: {type: String},
    vcard: {type: String}
  }),
  InputInvoiceMessageContent: new Schema({
    title: {type: String},
    description: {type: String},
    payload: {type: String},
    provider_token: {type: String},
    currency: {type: String},
    prices: {type: [LabeledPrice]},
    max_tip_amount: {type: Number},
    suggested_tip_amounts: {type: [Number]},
    provider_data: {type: String},
    photo_url: {type: String},
    photo_size: {type: Number},
    photo_width: {type: Number},
    photo_height: {type: Number},
    need_name: {type: Boolean},
    need_phone_number: {type: Boolean},
    need_email: {type: Boolean},
    need_shipping_address: {type: Boolean},
    send_phone_number_to_provider: {type: Boolean},
    send_email_to_provider: {type: Boolean},
    is_flexible: {type: Boolean}
  })
}
